### ISSUE TITLE
Create Login page

### ISSUE THREAD

**Issue by Edandevil** [Edandevil/Edandevil#1]

**Comment by Edandevil** [comment]
# Task assign

- [x] Draft issue title
- [x] https://github.com/octo-org/octo-repo/issues/45
- [x] Task assign need to complete

**Comment by Edandevil** [comment]
- [x] new task
- [ ] task to avoid
- [ ] create login page
